config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[create]
  end
  resources :bookmarks, only: %i[destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, dependent: :destroy, through: :bookmarks

  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  # def new
  #   @bookmark = Bookmark.new
  # end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    # @bookmark.list_id = params[:list_id]

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)

    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
Form from bookmarks#new

<div class="container">
  <h1><%= @list.name %></h1>

  <%= simple_form_for [@list, @bookmark] do |f| %>
  test
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-3">
  <h1>Lists</h1>
  <hr>

  <br>

  <% @lists.each do |list| %>
    <div class="card-product">
      <p><%= cl_image_tag(list.photo.key, crop: :thumb, gravity: :face) %></p>
      <div class="card-product-infos d-flex m-3">
        <h2><%= link_to list.name, list_path(list) %></h2>
      </div>
    </div>
  <% end %>

  <br>
  <hr>

  <%= link_to "Create a Movie List", new_list_path %>

  </a>
</div>

app/views/lists/new.html.erb
<div class="container mt-3">
  <h1>Create a new list</h1>

  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>

    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>

  <hr>


</div>


<%# GET /lists #index
GET /lists/123 #show
GET /lists/new #new
POST /lists #create %>

app/views/lists/show.html.erb
<div class="container mt-3">
  <h1><%= @list.name %></h1>

  <div class="show-img">
    <%= cl_image_tag(@list.photo.key, width: 250, height: 250) %>
  </div>

  <br>
  <p>Bookmarks</p>

  <% @list.bookmarks.each do |bookmark| %>

  <div>
    <h3>Movie name</h3>
    <h4>
      <%= bookmark.movie.title %>
    </h4>
    <img src="https://images.unsplash.com/photo-1692723258153-8ba8cce78bcd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY5MzgxOTk2Mw&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=100" alt="">
    <p><%= bookmark.comment %> </p>
    <br>

    <%= link_to "Delete", bookmark_path(bookmark),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %>
  </div>

    <%# <p>bookmark.id.comment</p> %>
  <% end %>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>

    <%= f.submit %>
  <% end %>


  <%= link_to "Back to Main Page", lists_path %>
</div>